"""Add indexes

Revision ID: 1c046fa5a56c
Revises: b7b2937cd40e
Create Date: 2025-05-17 13:10:03.738913

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c046fa5a56c"
down_revision: str | None = "b7b2937cd40e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_reviews_provider_id", "reviews", ["provider_id"], unique=False)
    op.create_index(
        "ix_tariffs_combined_search",
        "tariffs",
        ["speed", "price", "has_tv", "has_phone"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "ix_tariffs_price",
        "tariffs",
        ["price"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "ix_tariffs_provider_id",
        "tariffs",
        ["provider_id"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "ix_tariffs_speed",
        "tariffs",
        ["speed"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tariffs_speed",
        table_name="tariffs",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(
        "ix_tariffs_provider_id",
        table_name="tariffs",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(
        "ix_tariffs_price",
        table_name="tariffs",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(
        "ix_tariffs_combined_search",
        table_name="tariffs",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index("ix_reviews_provider_id", table_name="reviews")
    # ### end Alembic commands ###
