"""Add test providers and tariffs

Revision ID: 1dc96ea3a113
Revises: c99b74551be0
Create Date: 2025-05-09 17:25:24.750850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1dc96ea3a113"
down_revision: str | None = "c99b74551be0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column("promo_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column("tariffs", sa.Column("promo_period", sa.Integer(), nullable=True))
    op.drop_column("tariffs", "connection_type")
    op.drop_column("tariffs", "additional_services")
    op.drop_column("tariffs", "contract_period")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column("contract_period", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tariffs",
        sa.Column(
            "additional_services",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tariffs",
        sa.Column(
            "connection_type",
            postgresql.ENUM(
                "FTTH", "ADSL", "PON", "ETHERNET", "WIMAX", "LTE", name="connectiontype"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tariffs", "promo_period")
    op.drop_column("tariffs", "promo_price")
    # ### end Alembic commands ###
