"""Update Review model

Revision ID: 3dc067da3d85
Revises: d21a093e7d3b
Create Date: 2025-05-03 13:07:46.333916

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3dc067da3d85"
down_revision: str | None = "d21a093e7d3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_reviews_user_id"), "reviews", ["user_id", "provider_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_reviews_user_id"), "reviews", type_="unique")
    # ### end Alembic commands ###
