"""Add analytics

Revision ID: 494b840c824e
Revises: a6b0c5c27a02
Create Date: 2025-05-22 19:01:15.740372

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "494b840c824e"
down_revision: str | None = "a6b0c5c27a02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_clicks", sa.Integer(), nullable=False),
        sa.Column("click_path", sa.JSON(), nullable=False),
        sa.Column("user_path", sa.JSON(), nullable=False),
        sa.Column("goal_reached", sa.Boolean(), nullable=False),
        sa.Column("session_duration", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    op.create_index(
        op.f("ix_user_sessions_session_id"),
        "user_sessions",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_sessions_session_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
