"""Add tariffs

Revision ID: a6b0c5c27a02
Revises: 5ecf2e568cf7
Create Date: 2025-05-18 21:11:40.206694

"""

from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6b0c5c27a02"
down_revision: str | None = "5ecf2e568cf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    connection = op.get_bind()
    providers_result = connection.execute(
        sa.text("SELECT id, name FROM providers")
    ).fetchall()

    provider_ids = {row[1]: row[0] for row in providers_result}

    tariffs_table = sa.table(
        "tariffs",
        sa.column("id", sa.Uuid),
        sa.column("provider_id", sa.Uuid),
        sa.column("name", sa.String(255)),
        sa.column("description", sa.Text),
        sa.column("price", sa.Numeric(10, 2)),
        sa.column("speed", sa.Integer),
        sa.column("has_tv", sa.Boolean),
        sa.column("has_phone", sa.Boolean),
        sa.column("connection_cost", sa.Numeric(10, 2)),
        sa.column("promo_price", sa.Numeric(10, 2)),
        sa.column("promo_period", sa.Integer),
        sa.column("is_active", sa.Boolean),
        sa.column("url", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    rostelecom_tariffs = [
        {
            "id": uuid4(),
            "provider_id": provider_ids["Ростелеком"],
            "name": "Технологии доступа. Тест-драйв",
            "description": None,
            "price": 600,
            "speed": 100,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": 0,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": "https://volgograd.rt.ru/about_offer?offer=423396018814&cardId=a3aacba01c0719241c8eaccc66a7800921a33b02&lcs=active&pr7=POSTPAIDUNLIM&ref=/&tech=2&speed=100&cardPos=1",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Ростелеком"],
            "name": "Технологии развлечения. Тест-драйв",
            "description": None,
            "price": 700,
            "speed": 100,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": 0,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": "https://volgograd.rt.ru/about_offer?offer=423396722620&cardId=6162378429ddc6e57e8dfcb2c6317a17a217b41e&lcs=active&pr7=POSTPAIDUNLIM&ref=/&tech=2&speed=100&cardPos=2",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Ростелеком"],
            "name": "Технологии выгоды. Тест-драйв",
            "description": None,
            "price": 850,
            "speed": 100,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": 0,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": "https://volgograd.rt.ru/about_offer?offer=423397284606&cardId=24b1569bc1f9f148c8df82c8c228b5260a088032&lcs=active&pr7=POSTPAIDUNLIM&ref=/&tech=2&speed=100&cardPos=3",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Ростелеком"],
            "name": "Технологии доступа. Базовый",
            "description": None,
            "price": 600,
            "speed": 100,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": 0,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": "https://volgograd.rt.ru/about_offer?offer=423365747180&cardId=885469cfc704b330df743581afdd826d16ecb095&lcs=active&pr7=POSTPAIDUNLIM&ref=/&tech=2&speed=100&cardPos=4",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Ростелеком"],
            "name": "Игровой",
            "description": None,
            "price": 950,
            "speed": 100,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": 0,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": "https://volgograd.rt.ru/about_offer?offer=420390371540&cardId=9b80ea779806378a8a22a859481ccff09727f1fd&lcs=active&pr7=POSTPAIDUNLIM&ref=/&tech=2&speed=100&cardPos=5&gm=1",
        },
    ]

    dom_ru_tariffs = [
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 300 + ТВ",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1000,
            "speed": 300,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 500 + ТВ",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1200,
            "speed": 500,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 800 + ТВ",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1400,
            "speed": 800,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 1000 + ТВ",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1800,
            "speed": 1000,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 300",
            "description": "Тарифы с гигабитным интернетом",
            "price": 900,
            "speed": 300,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 500",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1050,
            "speed": 500,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 800",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1250,
            "speed": 800,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Дом.ru"],
            "name": "Гига 1000",
            "description": "Тарифы с гигабитным интернетом",
            "price": 1650,
            "speed": 1000,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": None,
            "promo_period": None,
            "is_active": True,
            "url": None,
        },
    ]

    mts_tariffs = [
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №1 - 100",
            "description": "Всё, что нужно в одном тарифе — связь, домашний интернет и ТВ",
            "price": 850,
            "promo_price": 425,
            "promo_period": 2,
            "speed": 100,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_1/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №1 - 200",
            "description": "Всё, что нужно в одном тарифе — связь, домашний интернет и ТВ",
            "price": 900,
            "promo_price": 475,
            "promo_period": 2,
            "speed": 200,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_1/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №1 - 500",
            "description": "Всё, что нужно в одном тарифе — связь, домашний интернет и ТВ",
            "price": 950,
            "promo_price": 525,
            "promo_period": 2,
            "speed": 500,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_1/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №1 - 1000",
            "description": "Всё, что нужно в одном тарифе — связь, домашний интернет и ТВ",
            "price": 1100,
            "promo_price": 675,
            "promo_period": 2,
            "speed": 1000,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_1/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №3 - 100",
            "description": "Быстрый интернет для вашего дома",
            "price": 600,
            "promo_price": None,
            "promo_period": None,
            "speed": 100,
            "has_tv": False,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_3/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №3 - 200",
            "description": "Быстрый интернет для вашего дома",
            "price": 650,
            "promo_price": None,
            "promo_period": None,
            "speed": 200,
            "has_tv": False,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_3/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №3 - 500",
            "description": "Быстрый интернет для вашего дома",
            "price": 700,
            "promo_price": None,
            "promo_period": None,
            "speed": 500,
            "has_tv": False,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_3/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №3 - 1000",
            "description": "Быстрый интернет для вашего дома",
            "price": 850,
            "promo_price": None,
            "promo_period": None,
            "speed": 1000,
            "has_tv": False,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_3/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №7 - 100",
            "description": "Быстрый домашний интернет, ТВ и большой пакет мобильной связи",
            "price": 950,
            "promo_price": 475,
            "promo_period": 2,
            "speed": 100,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_7/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №7 - 200",
            "description": "Быстрый домашний интернет, ТВ и большой пакет мобильной связи",
            "price": 1000,
            "promo_price": 525,
            "promo_period": 2,
            "speed": 200,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_7/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №7 - 500",
            "description": "Быстрый домашний интернет, ТВ и большой пакет мобильной связи",
            "price": 1050,
            "promo_price": 575,
            "promo_period": 2,
            "speed": 500,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_7/volgograd-city",
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["МТС"],
            "name": "Тариф №7 - 1000",
            "description": "Быстрый домашний интернет, ТВ и большой пакет мобильной связи",
            "price": 1200,
            "promo_price": 725,
            "promo_period": 2,
            "speed": 1000,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "is_active": True,
            "url": "https://volgograd.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/tarif_7/volgograd-city",
        },
    ]

    beeline_tariffs = [
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Весенний хит",
            "description": None,
            "price": 700,
            "speed": 100,
            "has_tv": True,
            "has_phone": True,
            "connection_cost": None,
            "promo_price": 425,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 200",
            "description": None,
            "price": 600,
            "speed": 200,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 300,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 300",
            "description": None,
            "price": 650,
            "speed": 300,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 325,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 500",
            "description": None,
            "price": 700,
            "speed": 500,
            "has_tv": False,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 350,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 200 с ТВ",
            "description": None,
            "price": 700,
            "speed": 200,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 350,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 300 с ТВ",
            "description": None,
            "price": 750,
            "speed": 300,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 375,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
        {
            "id": uuid4(),
            "provider_id": provider_ids["Билайн"],
            "name": "Для дома 500 с ТВ",
            "description": None,
            "price": 800,
            "speed": 500,
            "has_tv": True,
            "has_phone": False,
            "connection_cost": None,
            "promo_price": 400,
            "promo_period": 2,
            "is_active": True,
            "url": None,
        },
    ]

    all_tariffs = rostelecom_tariffs + dom_ru_tariffs + mts_tariffs + beeline_tariffs

    # Вставляем тарифы в таблицу
    op.bulk_insert(tariffs_table, all_tariffs)


def downgrade() -> None:
    """Downgrade schema."""
    # Собираем все имена тарифов, добавленные в upgrade
    rostelecom_tariff_names = [
        "Технологии доступа. Тест-драйв",
        "Технологии развлечения. Тест-драйв",
        "Технологии выгоды. Тест-драйв",
        "Технологии доступа. Базовый",
        "Игровой",
    ]

    dom_ru_tariff_names = [
        "Гига 300 + ТВ",
        "Гига 500 + ТВ",
        "Гига 800 + ТВ",
        "Гига 1000 + ТВ",
        "Гига 300",
        "Гига 500",
        "Гига 800",
        "Гига 1000",
    ]

    mts_tariff_names = [
        "Тариф №1 - 100",
        "Тариф №1 - 200",
        "Тариф №1 - 500",
        "Тариф №1 - 1000",
        "Тариф №3 - 100",
        "Тариф №3 - 200",
        "Тариф №3 - 500",
        "Тариф №3 - 1000",
        "Тариф №7 - 100",
        "Тариф №7 - 200",
        "Тариф №7 - 500",
        "Тариф №7 - 1000",
    ]

    beeline_tariff_names = [
        "Весенний хит",
        "Для дома 200",
        "Для дома 300",
        "Для дома 500",
        "Для дома 200 с ТВ",
        "Для дома 300 с ТВ",
        "Для дома 500 с ТВ",
    ]

    # Объединяем все имена тарифов в один список
    all_tariff_names = (
        rostelecom_tariff_names
        + dom_ru_tariff_names
        + mts_tariff_names
        + beeline_tariff_names
    )

    # Используем ANY для PostgreSQL вместо IN с кортежем
    delete_stmt = sa.text("DELETE FROM tariffs WHERE name = ANY(:names)")
    op.get_bind().execute(delete_stmt, {"names": all_tariff_names})
