"""Add cascade deletion

Revision ID: ac24564c3154
Revises: 3dc067da3d85
Create Date: 2025-05-03 17:50:47.848573

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ac24564c3154"
down_revision: str | None = "3dc067da3d85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_reviews_provider_id_providers", "reviews", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_reviews_provider_id_providers"),
        "reviews",
        "providers",
        ["provider_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_tariffs_provider_id_providers", "tariffs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tariffs_provider_id_providers"),
        "tariffs",
        "providers",
        ["provider_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tariffs_provider_id_providers"), "tariffs", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_tariffs_provider_id_providers",
        "tariffs",
        "providers",
        ["provider_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_reviews_provider_id_providers"), "reviews", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_reviews_provider_id_providers",
        "reviews",
        "providers",
        ["provider_id"],
        ["id"],
    )
    # ### end Alembic commands ###
