"""Make connection_cost nullable

Revision ID: b7b2937cd40e
Revises: e3f38065dede
Create Date: 2025-05-11 11:28:04.353577

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7b2937cd40e"
down_revision: str | None = "f0114287c0ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tariffs",
        "connection_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tariffs",
        "connection_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###
