"""Add phone to providers, make website and phone required

Revision ID: f0114287c0ac
Revises: a33c9b969062
Create Date: 2025-05-10 11:41:41.318677

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0114287c0ac"
down_revision: str | None = "a33c9b969062"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("providers", sa.Column("phone", sa.String(), nullable=False))
    op.alter_column(
        "providers", "website", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.add_column("tariffs", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariffs", "url")
    op.alter_column(
        "providers", "website", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("providers", "phone")
    # ### end Alembic commands ###
